### ISSUE TITLE
关于获取选中数据的问题

### ISSUE THREAD

**Issue by ZhenMrLee** [OCNYang/CartLayout#3]
构造方法中传的是树状的数据结构，我怎么样获取选中的数状数据，就是店铺里面有三个商品在购物车，但是要删除一个商品，我怎么样拿到这个店铺和这个商品，可能是我这边遍历的有问题，希望指教一下

**Comment by OCNYang** [comment]
[https://github.com/OCNYang/CartLayout/blob/master/cartlayout/src/main/java/com/ocnyang/cartlayout/CartAdapter.java#L117-L132](https://github.com/OCNYang/CartLayout/blob/master/cartlayout/src/main/java/com/ocnyang/cartlayout/CartAdapter.java#L117-L132)

**Comment by ZhenMrLee** [comment]
475972748  加个好友请教一下吧

**Comment by ZhenMrLee** [comment]
我需要把这些数据拿出来，而不是仅仅删除

**Comment by OCNYang** [comment]
最近工作忙，这是很简单的逻辑，你看看源代码就很清楚了。

```
new list;
for(item: mAdapter.getData())}{
    if (mDatas.get(i).isChecked()) {
        list.add(item);
        }
}
```
[伪代码]   

最终的新列表就是你选中要删除的数据。（在删除之前遍历）

**Comment by OCNYang** [comment]
或者你可以重写一下 Adapter 的 [removeChecked()](https://github.com/OCNYang/CartLayout/blob/master/cartlayout/src/main/java/com/ocnyang/cartlayout/CartAdapter.java#L117-L132) 的方法。例如：  

```
public List<ICartItem> removeChecked() {
        List<ICartItem> deleteList = new ArrayList<>();
        int iMax = mDatas.size() - 1;
        for (int i = iMax; i >= 0; i--) {
            if (mDatas.get(i).isChecked()) {
                deleteList.add(mDatas.get(i));
                mDatas.remove(i);
                notifyItemRemoved(i);
                notifyItemRangeChanged(i, mDatas.size());
            }
        }
        if (onCheckChangeListener != null) {
            onCheckChangeListener.onCalculateChanged(null);
        }
     return deleteList;
    }
```

使用上面这种方法不用单独遍历一遍了。在Github上直接敲的没验证，理论上是没问题的。
