### ISSUE TITLE
如果想点击组进行折叠  怎么搞

### ISSUE THREAD

**Issue by Quenstin** [OCNYang/CartLayout#5]
如果想点击组进行折叠  怎么搞

**Comment by OCNYang** [comment]
目前这个库没有实现此功能，但如果你在此库上拓展折叠的功能也是很简单的。
思路大概如此：
1. 获取都组下的全部商品的逻辑已经存在；
2. 只要在点击组时，把 1 中获取的条目全部隐藏就行了；
3. 给所有条目的 itemBean 添加一个控制显示隐藏的属性 isShow（在Adapter 通过此字段控制是否显示）。当需要隐藏某组下的商品条目时，把 1 中获取到的条目的 isShow 全部设置为 false。然后刷新Adapter就行了。

这个功能我会考虑在空闲时间在此库中添加。

**Comment by Quenstin** [comment]
感谢大神




| |
朱国庆
|
|
邮箱：13718132104@163.com
|

签名由 网易邮箱大师 定制

在2019年10月29日 09:09，藕心 写道：

目前这个库没有实现此功能，但如果你在此库上拓展折叠的功能也是很简单的。
思路大概如此：

获取都组下的全部商品的逻辑已经存在；
只要在点击组时，把 1 中获取的条目全部隐藏就行了；
给所有条目的 itemBean 添加一个控制显示隐藏的属性 isShow（在Adapter 通过此字段控制是否显示）。当需要隐藏某组下的商品条目时，把 1 中获取到的条目的 isShow 全部设置为 false。然后刷新Adapter就行了。

这个功能我会考虑在空闲时间在此库中添加。

**Comment by whb521** [comment]
大佬 分组折叠 怎么搞  隐藏条目以后 下面会空白

**Comment by OCNYang** [comment]
用 View.GONE 隐藏

**Comment by whb521** [comment]
> 用 View.GONE 隐藏

不知道view在哪里获取 是在 onBindViewHolder 里么

**Comment by OCNYang** [comment]
此库已升级，最新版本 v1.0.3 已支持折叠子条目，只需要通过 `mAdapter.setCanCollapsing(true);` 设置为可折叠即可。

**Comment by whb521** [comment]
> 此库已升级，最新版本 v1.0.3 已支持折叠子条目，只需要通过 `mAdapter.setCanCollapsing(true);` 设置为可折叠即可。

谢谢大佬
